### ISSUE TITLE
[Suggestion] :  Should throw errors as constants to simplify internationalization

### ISSUE THREAD

**Issue by mkhennoussi** [samuelgozi/firebase-auth-lite#18]
Hi guys, thanks again for these amazing libs.

Just a suggestion to throw errors as constants instead of using humanReadableErrors() function and errors.json file, here is the line:

`			if (!response.ok) {
				throw Error(humanReadableErrors[data.error.message] || data.error.message);
			}`

By using constants, it should be easier for developers to build their own error messages (with i18n for instance).

What do you think guys ?

**Comment by samuelgozi** [comment]
I agree with you, I didn't think about it. I'll try to make this change in the next few days.

**Comment by samuelgozi** [comment]
I pushed a commit that addresses this issue.
Now instead of hard coded messages in english the message will be the Firebase error code.
In addition I just added to the wiki a map that can be used as a reference to map the codes to user friendly errors: https://github.com/samuelgozi/firebase-auth-lite/wiki/Error-codes-map

Feel free to open an issue with different languages to add to the wiki(only if you want to). I might add a few on my own.

**Comment by samuelgozi** [comment]
Update: Just published the changes in version 0.8.1, make sure to update you dependencies.
I don't know if this counts as a breaking change, but error messages will appear differently(see previous comment).

This change not only helps internationalisation, but also reduced the size of the libs by about 24%(from 2.5KB to 1.9KB) which is awesome.
