### ISSUE TITLE
Fix docs and update dependencies

### ISSUE THREAD

**Issue by aidarkhanov** [samuelgozi/firebase-auth-lite#37]
Refactor code for existing users before releasing v1. Featuring #38

**Comment by samuelgozi** [comment]
I'm currently investing most of my (free) time on the Firestore library. After relasing it's v1 I'll switch to finishing the refactor of this library, which could be seen in branch `typescript`.

A few things to note about how this library is written.
As I outlined in the review of your code, this library is aggressively optimized for size and performance.
Many of the short-circuiting and weird syntax is for those reasons. I decided to trade **some** readability with smaller bundles, and this decision was made because I don't think that most developers dive into the code of this kind of libraries, and in addition, the library is small enough to reason about even with this "burden".

Now, many of the other style changes you suggested are purely that. They are style preferences which In my opinion don't make the code more readable, and also add up to bigger bundles.

For example replacing:
```js
if(x) return;
```

with:
```js
if(x) {
  return;
}
```

In my humble opinion doesn't seem to make the code more readable, and at the same time takes more space.
Also adding `else` statements for that matter. It is implied that everything outside of an if statement is an "else", and adding a code block for that adds size and complexity(because of scoping).

Thank you yet again for your good intentions. Many of your grammar changes are very welcome, and also some of your suggestions. Feel free to share your opinions on anything. And please open an issue before making changes, as I might be working some things already, and maybe some changes are not needed anyways(I've made the same mistake many times too).

**Comment by aidarkhanov** [comment]
Thank you! I made the changes for consistency's sake. You are welcome!

**Comment by samuelgozi** [comment]
@aidarkhanov I think well leave the logic for parsing the data to the adapter itself.
But all those changes should be done in the typescript branch. And I dont want to add any new dependencies to the project unless its 100% necessary so the adapter should implement the logic for working with indexedDB itself or be an external dependency altogether.

**Comment by aidarkhanov** [comment]
Closing the issue. Glad to help!
