### ISSUE TITLE
Feature Request: Authenticating with Phone Number

### ISSUE THREAD

**Issue by waleedshkt** [samuelgozi/firebase-auth-lite#56]
It is a great lib which offers all the main auth functionality of firebase-auth-sdk. But I've got a project where authenticating with phone number is required. But it's not included in your lib. I believe this lib to be providing all firebase sign-in methods will be a big plus

**Comment by samuelgozi** [comment]
I paused adding new features to the libs because of firebases move to create their own light weight libraries.
If they will not deliver I will resume the work on this one (I still fix bugs, and maintain it).

I remember that implementing SMS authentication was a little bit tricky. I will revise it today, and make a decision.
Thank you very much for the feature request, I appreciate the support.

**Comment by waleedshkt** [comment]
Looks like firebase has released their new modularized `exp` version containing `auth` lib.

Perhaps you're following the issue here: https://github.com/firebase/firebase-js-sdk/issues/332#issuecomment-738607863

**Comment by samuelgozi** [comment]
Yes I’m following it. Thanks.
