### ISSUE TITLE
0.8.8 released?

### ISSUE THREAD

**Issue by sesam** [samuelgozi/firebase-auth-lite#66]
Under releases, the last listed is 0.8.1, though in package.json I see 0.8.8 listed. What, other than time :), is needed before a 0.8.8 release?

Checking the README, I see the #2 is closed, so I got happy and started looking for a 1.0 version tag somewhere. Are there more things you want to change in the existing API? Any future cleanups are easy to handle with a major version bump. Accept the major version bumps into your life! 🎉

**Comment by samuelgozi** [comment]
Yes, and I will release 0.8.9 in a few minutes with dependencies updates (we only have dependencies for testing, nothing that goes into the client). Regarding v1.0, I was planning on migrating everything to typescript, and also make a few changes to the API and error handling, however I didn't work on it for a while, so that might change.

The typescript version can be seen in the "typescript" branch. Please feel free to ask any more questions or suggest something. I do read everything, it just takes me time to reply.
